services:
  migrations:
    build:
      context: .
      dockerfile: .dockerfile
    image: planner-rust-img
    user: root
    command: sh -c "mkdir -p /app/data && touch /app/data/database.db && chmod -R 777 /app/data && ls -la /app/data && ./migration-cli up"
    security_opt:
      - label:disable
    volumes:
      - planner-db:/app/data:Z
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:/app/data/database.db

  app:
    build:
      context: .
      dockerfile: .dockerfile
    image: planner-rust-img
    depends_on:
      migrations:
        condition: service_completed_successfully
    security_opt:
      - label:disable
    ports:
      - "8000:8000"
    volumes:
      - planner-db:/app/data:Z
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:/app/data/database.db
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000

volumes:
  planner-db:

