services:
    db:
        image: postgres:16-alpine
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports: 
            - "8080:8080"
        depends_on:
            - db

volumes:
    postgres_data:
