//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::goal::Entity as Goal;
pub use super::notes::Entity as Notes;
pub use super::reminder::Entity as Reminder;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
